services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: pgvector-db-guidex
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: embeddings_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d embeddings_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
